version: '3.1'

services:

  db:
    container_name: mysql-db
    image: mysql:8.0.28-oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000